"""Update participants table

Revision ID: 06fe6a5b8416
Revises: e80b63c9e011
Create Date: 2025-11-16 10:07:44.983707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fe6a5b8416'
down_revision: Union[str, Sequence[str], None] = 'e80b63c9e011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_link'), table_name='trips')
    op.drop_column('trips', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_trips_link'), 'trips', ['link'], unique=True)
    # ### end Alembic commands ###
