"""Remove constraint in expense description

Revision ID: 11bf70e05aa5
Revises: 4648e57b0642
Create Date: 2025-11-16 15:10:48.648309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bf70e05aa5'
down_revision: Union[str, Sequence[str], None] = '4648e57b0642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_description'), table_name='expenses')
    op.create_index(op.f('ix_expenses_description'), 'expenses', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_description'), table_name='expenses')
    op.create_index(op.f('ix_expenses_description'), 'expenses', ['description'], unique=True)
    # ### end Alembic commands ###
