"""Remove positions

Revision ID: 16976faf2e19
Revises: a7611ca35f20
Create Date: 2025-12-07 18:36:04.646062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16976faf2e19'
down_revision: Union[str, Sequence[str], None] = 'a7611ca35f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('expense_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('positions_expense_id_fkey')),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], name=op.f('positions_participant_id_fkey'))
    )
    # ### end Alembic commands ###
