"""Update positions table

Revision ID: 1d6f8a44c843
Revises: 06fe6a5b8416
Create Date: 2025-11-16 10:45:18.304297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6f8a44c843'
down_revision: Union[str, Sequence[str], None] = '06fe6a5b8416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'expense_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('positions', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_column('positions', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.alter_column('positions', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('positions', 'expense_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
