"""Add initiator_id to friends table

Revision ID: 38e453b722e1
Revises: 7ff9070b5fad
Create Date: 2025-11-27 08:15:10.120349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e453b722e1'
down_revision: Union[str, Sequence[str], None] = '7ff9070b5fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('initiator_id', sa.Integer(), nullable=False, server_default='21'))
    op.create_foreign_key(None, 'friends', 'users', ['initiator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_column('friends', 'initiator_id')
    # ### end Alembic commands ###
