"""Remove constraint in trips description

Revision ID: 4648e57b0642
Revises: 1d6f8a44c843
Create Date: 2025-11-16 15:01:15.452370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4648e57b0642'
down_revision: Union[str, Sequence[str], None] = '1d6f8a44c843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_trips_description'), table_name='trips')
    op.create_index(op.f('ix_trips_description'), 'trips', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_description'), table_name='trips')
    op.create_index(op.f('ix_trips_description'), 'trips', ['description'], unique=True)
    op.alter_column('expenses', 'total_cost',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
