"""Add ParticipantShare model

Revision ID: 4e48d0380238
Revises: 16976faf2e19
Create Date: 2025-12-07 18:55:30.807659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e48d0380238'
down_revision: Union[str, Sequence[str], None] = '16976faf2e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_shares',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('is_paying', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'trip_id'], ['participants.user_id', 'participants.trip_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'trip_id', 'expense_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_shares')
    # ### end Alembic commands ###
