"""Limit length of username (40) and trip name (100)

Revision ID: 7eb0c6d5c4e4
Revises: cce3935ea2e9
Create Date: 2025-11-18 07:49:47.601088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb0c6d5c4e4'
down_revision: Union[str, Sequence[str], None] = 'cce3935ea2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
