"""Add is_accepted to friends table

Revision ID: 7ff9070b5fad
Revises: de56df9253b8
Create Date: 2025-11-27 07:57:33.258736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff9070b5fad'
down_revision: Union[str, Sequence[str], None] = 'de56df9253b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('is_accepted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'is_accepted')
    # ### end Alembic commands ###
