"""Add dates to trip

Revision ID: be21c780eeb5
Revises: 7eb0c6d5c4e4
Create Date: 2025-11-18 08:01:10.122533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be21c780eeb5'
down_revision: Union[str, Sequence[str], None] = '7eb0c6d5c4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('beginning_date', sa.Date(), nullable=True))
    op.add_column('trips', sa.Column('end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_trips_beginning_date'), 'trips', ['beginning_date'], unique=False)
    op.create_index(op.f('ix_trips_end_date'), 'trips', ['end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_end_date'), table_name='trips')
    op.drop_index(op.f('ix_trips_beginning_date'), table_name='trips')
    op.drop_column('trips', 'end_date')
    op.drop_column('trips', 'beginning_date')
    # ### end Alembic commands ###
